### ISSUE TITLE
Can't extract single line data from invoices

### ISSUE THREAD

**Issue by priyanshuchauhan** [m3nu/invoice2data#57]
I'm able to extract all the data from invoice PDF except **lines** part. 
Below is the line template. I've tested the regex on https://regex101.com/ and it works fine.

Template
```
lines:
  start: RETOUR
  end: Totaal Overzicht
  line: ^(?P<INVOICE_QUANTITY>\d+.\S)(?P<INVOICE_ID>\d+.\s)(?P<DESCRIPTION>\w+.*\s)(?P<GROSS_UNUSED>\w+.*\s)(?P<PRICE>\w+.*\s)(?P<AMOUNT>\w+.*\s)(?P<TAX_PERCENTAGE>\S+)
```
No line in result.

But if I add simple parsing 
` line: (.*\d\S) `
then I get empty results
`'lines': [{}, {}, {}, {}, {}, {}, {}, {}, {}], `

Is it because of regex? All the sample templates either don't have lines or have multi line with _first_line, last_line_
Can someone push me right direction or give an example?

**Comment by priyanshuchauhan** [comment]
@alexis-via, @m3nu, @hbrunn can anyone of you please take a look?

**Comment by m3nu** [comment]
That's @hbrunn 's feature. He will advise.

Maybe you have some settings to remove whitespace. I must admit I didn't look into this feature at all so far.

**Comment by hbrunn** [comment]
you will want to post the text you want to identify, as well as the debug output after the pdf2text step and eventual whitespace removal. Otherwise that's all guesswork.

**Comment by priyanshuchauhan** [comment]
Thanks for quick response.
@hbrunn below is pdf2text portion that I want to parse. White spaces are not removed during extraction:

```
Kieler Bocht 43
9723 JA Groningen
T 050-5445757. F 050-4061102
Internet: www.xx.nl
E-mail: aaa@fff.nl
KvK 17093426. BTW NL006300170B01
IBAN NL37CITI0266064760
BIC/SWIFT-Code CITINL2X
Citibank nr. 26.60.64.760



          Factuur                                                                                Nr. : 94011127 / 12.06.2017
          Woodstone Pizza Almere B.V.                                                              Afleveradres goederen:
                                                                                                   Woodstone Pizza and Wine Almere
          Woodstone Pizza and Wine Almere                                                          Belfort 13
          Passage 5                                                                                1315 VA ALMERE
          2042 KS ZANDVOORT




Artikel      Omschrijving                                              Aantal      Inhoud       Alc%      Emb.Bedrag           Br.Prijs                 Netto bedr.


RETOUR
Leveringnummer 0016032216            Afleverdatum              12.06.2017                  Referentie            PDA 0003008905
9109       Emballage Krat 3,90 EURO                                            3                                 11,70-    0,00                               0,00
9111       Emballage Krat 5,00 EURO                                           31                                155,00-    0,00                               0,00
9402       VBR Bier, Hele Krat 0,30 EURO                                       2                                           0,30-                              0,60-   H

                                Totaal Overzicht
```

Template:
```
# -*- coding: utf-8 -*-
issuer: De Klok Dranken
fields:
  amount: Totaal.*(\d{2})+$
  date: Nr.+(\d{2}.\d{1,2}.\d{4})
  invoice_number: Nr.+(\d{8}).
  supplier_address: adres\s+(.+)
  TELE_PHONE: T\s(\d{4}-\d{6})
  TELE_FAX: F\s(\d{4}-\d{6})
  WEBSITE_URI: 'Internet: (\S*)'
  EMAIL: E-mail:\s+(.+)
  IBAN: IBAN\s+(.+)
  BIC: BIC\/SWIFT-Code +([^\s]+)
  BTW: BTW\s+(.+)
  KvK: KvK\s+(.+)BTW
lines:
  start: RETOUR
  end: Totaal Overzicht
  line: ^(?P<INVOICE_QUANTITY>\d+.\S)(?P<INVOICE_ID>\d+.\s)(?P<DESCRIPTION>\w+.*\s)(?P<GROSS_UNUSED>\w+.*\s)(?P<PRICE>\w+.*\s)(?P<AMOUNT>\w+.*\s)(?P<TAX_PERCENTAGE>\S+)
  # line: (.*\d\s\S)
keywords:
  - Dranken
options:
  currency: EUR
  date_formats:
    - '%d-%m-%Y'
  languages:
    - nl
  decimal_separator: ','

```
My result:
 `{'BTW': u'NL006300170B01', 'supplier_address': u'goederen:', 'BIC': u'CITINL2X', 'KvK': u'17093426. ', 'currency': 'EUR', 'IBAN': u'NL37CITI0266064760', 'date': datetime.datetime(2017, 6, 12, 0, 0), 'invoice_number': u'94011127', 'desc': u'Invoice 94011127 from De Klok Dranken', 'WEBSITE_URI': u'www.fff.nl', 'EMAIL': ffff@fff.nl', 'issuer': 'De Klok Dranken'}`
